#!/usr/bin/python
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy 1 yyds")
print("jzy f yyds")
print("jzy f yyds")
print("jzy f yyds")
